target := "native"

default: check test

fmt:
    moon fmt

check:
    moon check --deny-warn --target {{target}}

test:
    moon test --target {{target}}

run:
    moon run src/cmd/oden --target {{target}}

info:
    moon info --target {{target}}

bench:
    node scripts/bench-run.mjs
